name: Build FoxFS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build FoxFS
      run: |
        msbuild FoxFS.sln /p:Configuration=Release /p:Platform="Win32"

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: FoxFSArchiver-Exe
        path: |
          **/*.exe
          !**/obj/**
